[general]
live_config_reload = true

[window]
padding = { x = 0 , y = 0 }
dynamic_padding = true 

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}
bold = { family = "JetBrainsMono Nerd Font", style = "Bold"}
italic = { family = "JetBrainsMono Nerd Font", style = "Italic"}
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic"}
size = 11.5

[keyboard]
bindings = [
  { key = "Back", mods = "Control", chars = "\u0017" }
]

# [selection]
# save_to_clipboard = false 

# [cursor]
# style = {shape= "Block"}

# [terminal]
# osc52 = "CopyPaste"

# [mouse]
# hide_when_typing = true




# -----------------------------------------------------------------------------
# Theme: Tokyo Night
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'


